import Sheet from "./components/Sheet";
import Navigation from "./components/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`inter.className  `}>
        <main className="relative mx-2 min-h-screen md:max-w-4xl sm:max-w-none lg:max-w-6xl flex-col  md:mx-4 md:mt-0 md:flex-row  lg:mx-auto ">
        <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
